
export const CASINO_PROVIDER = "CASINO_PROVIDER"
export const CASINO_TYPES = "CASINO_TYPES"
export const CASINO_GET_ALL_DATA = "CASINO_GET_ALL_DATA"
export const CASINO_SETPROVIDER = "CASINO_SETPROVIDER"
export const CASINO_GET_DATA = "CASINO_GET_DATA"
export const CASINO_FILTER_DATA = "CASINO_FILTER_DATA"
export const CASINO_TYPE  = "CASINO_TYPE"
export const CASINO_DATA_FORMAT  = "CASINO_DATA_FORMAT"

//sports
export const SPORTS_LIST = "SPORTS_LIST"
export const SET_ALL_MATCHS = "SET_ALL_MATCHS"
export const ALL_SPORT_LIST = "ALL_SPORT_LIST"
export const CURRENT_SELECT_SPORT = "CURRENT_SELECT_SPORT"
export const CURRENT_TAP_CHANGE = "CURRENT_TAP_CHANGE"
export const SEASON_TAB_CHANGE = "seasonTabChange"
export const MARKET_TAB_CHANGE = "marketTabChange"
export const CURRENTSELECTEGAME = "CURRENTSELECTEGAME"
export const SPORTS_SIDEBAR_SET_ITEM = "SPORTS_SIDEBAR_SET_ITEM"
export const CURRENT_BET_TYPE = "CURRENT_BET_TYPE"
export const REFRESH_BET_ID = "REFRESH_BET_ID"
export const SPORTSBOOK_BET_HISTORY = "SPORTSBOOK_BET_HISTORY"
export const RECOVERYEVENTUPDATE = "RECOVERYEVENTUPDATE"
export const FEATURED_EVENT_DATA = "FEATURED_EVENT_DATA"
export const CHANGE_CURRENT_COUNTRY = "CHANGE_CURRENT_COUNTRY"
export const FIRSTPAGE_SPORTS = "FIRSTPAGE_SPORTS"
export const SET_BETSLIP_LOADING = "SET_BETSLIP_LOADING"

//first page

export const FIRSTPAGESLIDER = "FIRSTPAGESLIDER"
export const FIRSTPAGEDATA = "FIRSTPAGEDATA"
export const FIRSTPAGEGAMELIST = "FIRSTPAGEGAMELIST"
export const FIRSTPAGEGETSIDEBAR = "FIRSTPAGEGETSIDEBAR"

